import { mutation } from "./_generated/server";
import { v } from "convex/values";

// Seed the database with sample data
export const seedDatabase = mutation({
  args: {},
  handler: async (ctx) => {
    // Check if data already exists
    const existingAssets = await ctx.db.query("hydrogenAssets").collect();
    if (existingAssets.length > 0) {
      return "Database already has data";
    }

    const now = Date.now();

    // Add sample hydrogen assets
    await ctx.db.insert("hydrogenAssets", {
      name: "Gujarat Green Hydrogen Hub",
      type: "plant",
      location: {
        lat: 23.0225,
        lng: 72.5714,
        address: "Kutch District, Gujarat",
        state: "Gujarat",
        district: "Kutch",
      },
      capacity: 1000,
      status: "planned",
      operator: "Adani Green Energy",
      renewableScore: 85,
      transportScore: 75,
      environmentalRisk: 25,
      createdAt: now,
      updatedAt: now,
    });

    await ctx.db.insert("hydrogenAssets", {
      name: "Rajasthan Solar H2 Plant",
      type: "plant",
      location: {
        lat: 27.0238,
        lng: 74.2179,
        address: "Jaisalmer, Rajasthan",
        state: "Rajasthan",
        district: "Jaisalmer",
      },
      capacity: 500,
      status: "under_construction",
      operator: "NTPC Limited",
      renewableScore: 90,
      transportScore: 60,
      environmentalRisk: 20,
      createdAt: now,
      updatedAt: now,
    });

    // Add sample demand clusters
    const demandClusters = [
      {
        name: "Mumbai Industrial Complex",
        type: "industrial" as const,
        location: {
          lat: 19.0760,
          lng: 72.8777,
          address: "Mumbai, Maharashtra",
          state: "Maharashtra",
          district: "Mumbai",
        },
        currentDemand: 50000,
        projectedDemand2030: 150000,
        projectedDemand2050: 400000,
        industries: ["Steel", "Petrochemicals", "Refining"],
        transportConnectivity: 90,
        priority: "high" as const,
      },
      {
        name: "Delhi NCR Transport Hub",
        type: "transport" as const,
        location: {
          lat: 28.7041,
          lng: 77.1025,
          address: "New Delhi, Delhi",
          state: "Delhi",
          district: "New Delhi",
        },
        currentDemand: 35000,
        projectedDemand2030: 120000,
        projectedDemand2050: 350000,
        industries: ["Public Transport", "Logistics", "Aviation"],
        transportConnectivity: 95,
        priority: "high" as const,
      },
      {
        name: "Ahmedabad Industrial Zone",
        type: "industrial" as const,
        location: {
          lat: 23.0225,
          lng: 72.5714,
          address: "Ahmedabad, Gujarat",
          state: "Gujarat",
          district: "Ahmedabad",
        },
        currentDemand: 42000,
        projectedDemand2030: 140000,
        projectedDemand2050: 380000,
        industries: ["Chemicals", "Textiles", "Pharmaceuticals"],
        transportConnectivity: 85,
        priority: "high" as const,
      },
      {
        name: "Chennai Port Complex",
        type: "export" as const,
        location: {
          lat: 13.0827,
          lng: 80.2707,
          address: "Chennai, Tamil Nadu",
          state: "Tamil Nadu",
          district: "Chennai",
        },
        currentDemand: 28000,
        projectedDemand2030: 95000,
        projectedDemand2050: 280000,
        industries: ["Shipping", "Export", "Port Operations"],
        transportConnectivity: 92,
        priority: "high" as const,
      },
      {
        name: "Bangalore Tech District",
        type: "residential" as const,
        location: {
          lat: 12.9716,
          lng: 77.5946,
          address: "Bangalore, Karnataka",
          state: "Karnataka",
          district: "Bangalore Urban",
        },
        currentDemand: 18000,
        projectedDemand2030: 65000,
        projectedDemand2050: 180000,
        industries: ["IT Services", "Data Centers", "Commercial"],
        transportConnectivity: 88,
        priority: "medium" as const,
      },
      {
        name: "Kolkata Steel Belt",
        type: "industrial" as const,
        location: {
          lat: 22.5726,
          lng: 88.3639,
          address: "Kolkata, West Bengal",
          state: "West Bengal",
          district: "Kolkata",
        },
        currentDemand: 55000,
        projectedDemand2030: 175000,
        projectedDemand2050: 450000,
        industries: ["Steel", "Heavy Engineering", "Mining"],
        transportConnectivity: 78,
        priority: "high" as const,
      },
      {
        name: "Pune Automotive Cluster",
        type: "industrial" as const,
        location: {
          lat: 18.5204,
          lng: 73.8567,
          address: "Pune, Maharashtra",
          state: "Maharashtra",
          district: "Pune",
        },
        currentDemand: 32000,
        projectedDemand2030: 110000,
        projectedDemand2050: 290000,
        industries: ["Automotive", "Manufacturing", "Engineering"],
        transportConnectivity: 82,
        priority: "medium" as const,
      },
      {
        name: "Hyderabad Pharma Valley",
        type: "industrial" as const,
        location: {
          lat: 17.3850,
          lng: 78.4867,
          address: "Hyderabad, Telangana",
          state: "Telangana",
          district: "Hyderabad",
        },
        currentDemand: 25000,
        projectedDemand2030: 85000,
        projectedDemand2050: 240000,
        industries: ["Pharmaceuticals", "Biotechnology", "Chemicals"],
        transportConnectivity: 80,
        priority: "medium" as const,
      },
      {
        name: "Jaipur Transport Network",
        type: "transport" as const,
        location: {
          lat: 26.9124,
          lng: 75.7873,
          address: "Jaipur, Rajasthan",
          state: "Rajasthan",
          district: "Jaipur",
        },
        currentDemand: 22000,
        projectedDemand2030: 78000,
        projectedDemand2050: 210000,
        industries: ["Public Transport", "Tourism", "Logistics"],
        transportConnectivity: 75,
        priority: "medium" as const,
      },
      {
        name: "Kochi Port and Shipping",
        type: "export" as const,
        location: {
          lat: 9.9312,
          lng: 76.2673,
          address: "Kochi, Kerala",
          state: "Kerala",
          district: "Ernakulam",
        },
        currentDemand: 24000,
        projectedDemand2030: 82000,
        projectedDemand2050: 230000,
        industries: ["Shipping", "Spices Export", "Tourism"],
        transportConnectivity: 85,
        priority: "medium" as const,
      },
      {
        name: "Lucknow Urban Zone",
        type: "residential" as const,
        location: {
          lat: 26.8467,
          lng: 80.9462,
          address: "Lucknow, Uttar Pradesh",
          state: "Uttar Pradesh",
          district: "Lucknow",
        },
        currentDemand: 16000,
        projectedDemand2030: 58000,
        projectedDemand2050: 165000,
        industries: ["Government", "Education", "Healthcare"],
        transportConnectivity: 70,
        priority: "low" as const,
      },
      {
        name: "Visakhapatnam Steel Complex",
        type: "industrial" as const,
        location: {
          lat: 17.6868,
          lng: 83.2185,
          address: "Visakhapatnam, Andhra Pradesh",
          state: "Andhra Pradesh",
          district: "Visakhapatnam",
        },
        currentDemand: 48000,
        projectedDemand2030: 160000,
        projectedDemand2050: 420000,
        industries: ["Steel", "Petrochemicals", "Fertilizers"],
        transportConnectivity: 88,
        priority: "high" as const,
      },
      {
        name: "Bhubaneswar Government Hub",
        type: "residential" as const,
        location: {
          lat: 20.2961,
          lng: 85.8245,
          address: "Bhubaneswar, Odisha",
          state: "Odisha",
          district: "Khordha",
        },
        currentDemand: 14000,
        projectedDemand2030: 52000,
        projectedDemand2050: 148000,
        industries: ["Government", "IT Services", "Education"],
        transportConnectivity: 72,
        priority: "low" as const,
      },
      {
        name: "Indore Commercial District",
        type: "residential" as const,
        location: {
          lat: 22.7196,
          lng: 75.8577,
          address: "Indore, Madhya Pradesh",
          state: "Madhya Pradesh",
          district: "Indore",
        },
        currentDemand: 19000,
        projectedDemand2030: 68000,
        projectedDemand2050: 195000,
        industries: ["Trade", "Finance", "Textiles"],
        transportConnectivity: 76,
        priority: "medium" as const,
      },
      {
        name: "Chandigarh Transport System",
        type: "transport" as const,
        location: {
          lat: 30.7333,
          lng: 76.7794,
          address: "Chandigarh, Punjab",
          state: "Punjab",
          district: "Chandigarh",
        },
        currentDemand: 15000,
        projectedDemand2030: 55000,
        projectedDemand2050: 155000,
        industries: ["Public Transport", "Government", "Education"],
        transportConnectivity: 78,
        priority: "low" as const,
      },
      {
        name: "Coimbatore Textile Hub",
        type: "industrial" as const,
        location: {
          lat: 11.0168,
          lng: 76.9558,
          address: "Coimbatore, Tamil Nadu",
          state: "Tamil Nadu",
          district: "Coimbatore",
        },
        currentDemand: 28000,
        projectedDemand2030: 95000,
        projectedDemand2050: 270000,
        industries: ["Textiles", "Engineering", "Automotive Parts"],
        transportConnectivity: 79,
        priority: "medium" as const,
      },
      {
        name: "Guwahati Northeast Gateway",
        type: "transport" as const,
        location: {
          lat: 26.1445,
          lng: 91.7362,
          address: "Guwahati, Assam",
          state: "Assam",
          district: "Kamrup",
        },
        currentDemand: 12000,
        projectedDemand2030: 45000,
        projectedDemand2050: 130000,
        industries: ["Logistics", "Oil Refining", "Tea Processing"],
        transportConnectivity: 65,
        priority: "low" as const,
      },
      {
        name: "Surat Diamond and Textile Zone",
        type: "industrial" as const,
        location: {
          lat: 21.1702,
          lng: 72.8311,
          address: "Surat, Gujarat",
          state: "Gujarat",
          district: "Surat",
        },
        currentDemand: 38000,
        projectedDemand2030: 125000,
        projectedDemand2050: 340000,
        industries: ["Diamonds", "Textiles", "Chemicals"],
        transportConnectivity: 84,
        priority: "high" as const,
      },
      {
        name: "Kandla Port Export Terminal",
        type: "export" as const,
        location: {
          lat: 23.0330,
          lng: 70.2167,
          address: "Kandla, Gujarat",
          state: "Gujarat",
          district: "Kutch",
        },
        currentDemand: 26000,
        projectedDemand2030: 88000,
        projectedDemand2050: 250000,
        industries: ["Port Operations", "Chemicals Export", "Petroleum"],
        transportConnectivity: 90,
        priority: "high" as const,
      },
      {
        name: "Nashik Industrial Estate",
        type: "industrial" as const,
        location: {
          lat: 19.9975,
          lng: 73.7898,
          address: "Nashik, Maharashtra",
          state: "Maharashtra",
          district: "Nashik",
        },
        currentDemand: 21000,
        projectedDemand2030: 72000,
        projectedDemand2050: 205000,
        industries: ["Automotive", "Wine", "Engineering"],
        transportConnectivity: 77,
        priority: "low" as const,
      },
      {
        name: "Thiruvananthapuram IT Corridor",
        type: "residential" as const,
        location: {
          lat: 8.5241,
          lng: 76.9366,
          address: "Thiruvananthapuram, Kerala",
          state: "Kerala",
          district: "Thiruvananthapuram",
        },
        currentDemand: 13000,
        projectedDemand2030: 48000,
        projectedDemand2050: 140000,
        industries: ["IT Services", "Space Technology", "Tourism"],
        transportConnectivity: 73,
        priority: "low" as const,
      },
      {
        name: "Rourkela Steel City",
        type: "industrial" as const,
        location: {
          lat: 22.2604,
          lng: 84.8536,
          address: "Rourkela, Odisha",
          state: "Odisha",
          district: "Sundargarh",
        },
        currentDemand: 45000,
        projectedDemand2030: 155000,
        projectedDemand2050: 410000,
        industries: ["Steel", "Heavy Engineering", "Mining"],
        transportConnectivity: 75,
        priority: "high" as const,
      },
      {
        name: "Mangalore Port Complex",
        type: "export" as const,
        location: {
          lat: 12.9141,
          lng: 74.8560,
          address: "Mangalore, Karnataka",
          state: "Karnataka",
          district: "Dakshina Kannada",
        },
        currentDemand: 23000,
        projectedDemand2030: 79000,
        projectedDemand2050: 225000,
        industries: ["Port Operations", "Petrochemicals", "Coffee Export"],
        transportConnectivity: 86,
        priority: "medium" as const,
      },
      {
        name: "Rajkot Engineering Hub",
        type: "industrial" as const,
        location: {
          lat: 22.3039,
          lng: 70.8022,
          address: "Rajkot, Gujarat",
          state: "Gujarat",
          district: "Rajkot",
        },
        currentDemand: 29000,
        projectedDemand2030: 98000,
        projectedDemand2050: 275000,
        industries: ["Engineering", "Automotive Parts", "Machine Tools"],
        transportConnectivity: 81,
        priority: "medium" as const,
      },
      {
        name: "Agra Tourism and Heritage Zone",
        type: "residential" as const,
        location: {
          lat: 27.1767,
          lng: 78.0081,
          address: "Agra, Uttar Pradesh",
          state: "Uttar Pradesh",
          district: "Agra",
        },
        currentDemand: 17000,
        projectedDemand2030: 61000,
        projectedDemand2050: 175000,
        industries: ["Tourism", "Handicrafts", "Leather"],
        transportConnectivity: 74,
        priority: "low" as const,
      }
    ];

    // Insert all demand clusters
    for (const cluster of demandClusters) {
      await ctx.db.insert("demandClusters", {
        name: cluster.name,
        type: cluster.type as "industrial" | "residential" | "transport" | "export",
        location: cluster.location,
        currentDemand: cluster.currentDemand,
        projectedDemand2030: cluster.projectedDemand2030,
        projectedDemand2050: cluster.projectedDemand2050,
        industries: cluster.industries,
        transportConnectivity: cluster.transportConnectivity,
        priority: cluster.priority as "low" | "medium" | "high",
        createdAt: now,
        updatedAt: now,
      });
    }

    // Add sample renewable potential
    await ctx.db.insert("renewablePotential", {
      location: {
        lat: 27.0238,
        lng: 74.2179,
        state: "Rajasthan",
        district: "Jaisalmer",
      },
      solarIrradiance: 6.2,
      windSpeed: 8.5,
      solarPotential: 5000,
      windPotential: 3000,
      landAvailability: 100,
      gridConnectivity: 75,
      waterAvailability: 60,
      overallScore: 85,
      createdAt: now,
      updatedAt: now,
    });

    // Add sample transport infrastructure
    await ctx.db.insert("transportInfra", {
      name: "Mumbai Port",
      type: "port",
      geometry: {
        type: "Point",
        coordinates: [72.8777, 19.0760],
      },
      location: {
        state: "Maharashtra",
        district: "Mumbai",
      },
      connectivity: 95,
      strategicImportance: 90,
      capacity: 50000000,
      createdAt: now,
      updatedAt: now,
    });

    // Add sample policy data
    await ctx.db.insert("policyData", {
      state: "Gujarat",
      policies: [
        {
          name: "Gujarat Hydrogen Policy 2023",
          type: "subsidy",
          description: "25% capital subsidy for green hydrogen projects",
          value: "25%",
          effectiveDate: "2023-01-01",
          expiryDate: "2030-12-31",
        },
      ],
      incentiveScore: 85,
      regulatoryClarity: 80,
      targetAmbition: 90,
      overallScore: 85,
      jobCreationPotential: 60,
      sdgAlignment: {
        sdg7: 90,
        sdg9: 80,
        sdg13: 85,
      },
      createdAt: now,
      updatedAt: now,
    });

    return "Sample data seeded successfully";
  },
});
